run:
  timeout: 10m
  deadline: 5m
linters:
  enable-all: true
  disable:
    - wrapcheck
    - gochecknoinits
    - varnamelen
    - exhaustruct
    - ireturn
    - gochecknoglobals
    - funlen
    - forbidigo
    - gomoddirectives
    - depguard
    # deprecated
    - execinquery
    - gomnd
    - exportloopref
    - rowserrcheck
    - wastedassign
linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      # Used in HTTP handlers, any error is handled by the server itself.
      - (net/http.ResponseWriter).Write
      # Never check the logger error.
      - (github.com/go-kit/log.Logger).Log
  nolintlint:
    require-specific: true

issues:
  exclude-files:
    - ".*_test.go"
