name: validate pull requests
on:
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/containers/podman:v4
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
      - uses: actions/checkout@v3
      - run: |
          yum -y install make gcc glib2-devel glibc-devel glibc-static device-mapper-devel
          export GOBIN=$(pwd)/bin/
          export CGO_ENABLED=1
          make .install.ginkgo
          make test-unit
